### ISSUE TITLE
Update to 5.0 fails

### ISSUE THREAD

**Issue by bay73** [freaktechnik/eslint-plugin-array-func#505]
Updating version of the eslint-plugin-array-func from 4.0.0 to 5.0.1 causes failures while executing lint (everything works fine in case of 4.0.0):
```
ESLint: 8.57.0
Error [ERR_REQUIRE_ESM]: require() of ES Module /node_modules/eslint-plugin-array-func/index.js from/node_modules/@eslint/eslintrc/dist/eslintrc.cjs not supported.
Instead change the require of index.js in /node_modules/@eslint/eslintrc/dist/eslintrc.cjs to a dynamic import() which is available in all CommonJS modules.
    at ConfigArrayFactory._loadPlugin (/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3433:42)
    at /node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3304:33
    at Array.reduce (<anonymous>)
    at ConfigArrayFactory._loadPlugins (/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3300:22)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3100:[44]

```
We are using "eslint": "8.57.0"

Do you have any suggestion how this can be fixed?

**Comment by freaktechnik** [comment]
If you want to use common JS to configure eslint you will probably have to follow what the error there recommends.
